#!/bin/bash

for amount in 1000 10000 100000 1000000 5000000 10000000
do
        echo "$amount";
	for i in {1..5}
	do
            x=`(time ./combigen.exe -i example_data/combinations.json -r $amount > output.txt) 2>&1 | grep real | cut -f2`
            echo $x
	done
        echo
done
rm output.txt

